version: "3.9"
services:
  db:
    container_name: getgo-pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: getgo-pg
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:v4.15.2
    profiles: [ "tools" ]
    volumes:
      - ./api/data/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/getgo-pg?sslmode=disable",
      ]
    command: [ "up" ]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  api:
    container_name: getgo-api
    ports:
      - "3003:3003"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  data:
